POST {{host}}/users/{{userId}}/subscriptions/{{subscriptionId}}/reminders
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "text": "Tell my wife I love her",
    "dateTime": "2026-03-16T22:20:09"
}